import { useRef, useState } from "react";
import { ELEMENTS, EXTRA_STORIES, type ElementStory } from "./elements";
import { everydayElement } from "./everydayElements";
import EverydayIllustration from "./EverydayIllustration";
import { Sources, type Navigate } from "./shared";

const STORAGE = "prism.observatory.discoveries.v1";
const CASES = [
  { clue: "일부 멍게류가 농축하고, 이름에는 바나디스가 남았습니다.", symbol: "V" },
  { clue: "아르헨티나의 이름과 라틴어 뿌리를 공유합니다. 조선의 두 기술자 이야기에도 등장합니다.", symbol: "Ag" },
  { clue: "공기의 약 78%를 차지하지만, 분자의 강한 결합을 풀어 쓰기 좋은 재료로 바꾸는 일이 필요합니다.", symbol: "N" },
  { clue: "이 원소의 133 동위원소에 정한 전이 진동수로 1초를 정의합니다.", symbol: "Cs" },
  { clue: "태양의 스펙트럼에서 먼저 단서를 찾았고, 지구에서 뒤에 확인된 원소입니다.", symbol: "He" },
];
function savedDiscoveries(): string[] {
  try { const value: unknown = JSON.parse(localStorage.getItem(STORAGE) || "[]"); return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string" && ELEMENTS.some(e => e.symbol === item)) : []; } catch { return []; }
}
function ElementIllustration({ element }: { element: ElementStory }) {
  const symbol = element.symbol;
  const kind = symbol === "V" ? "sea" : symbol === "Ag" ? "silver" : ["N", "P", "K"].includes(symbol) ? "grain" : ["Li", "Co", "Ni", "Mn"].includes(symbol) ? "battery" : ["Si", "Ge", "Ga", "In"].includes(symbol) ? "chip" : ["H", "He"].includes(symbol) ? "star" : ["Fe", "Nd", "Sm", "Gd"].includes(symbol) ? "magnet" : element.number > 83 ? "nucleus" : "crystal";
  const caption = { sea: "바닷속 농축 능력의 이야기", silver: "은을 분리하는 제련의 이야기", grain: "원소와 자라는 생명의 연결", battery: "전자와 에너지를 담는 재료", chip: "작은 회로를 만드는 원소", star: "별의 빛으로 이어지는 원소", magnet: "자성을 만드는 재료", nucleus: "원자핵을 탐구하는 실험실", crystal: "물질과 구조를 떠올리는 결정" }[kind];
  return <figure className="element-illustration"><svg viewBox="0 0 360 240" role="img" aria-label={`${element.name}: ${caption} 개념 그림`}>
    <defs><radialGradient id="element-glow"><stop stopColor="#a798d8" stopOpacity=".22" /><stop offset="1" stopColor="#101521" stopOpacity="0" /></radialGradient></defs><circle cx="180" cy="120" r="114" fill="url(#element-glow)" />
    {kind === "sea" && <g><path d="M40 187Q110 172 180 190T320 187" fill="none" stroke="#76b9c1" strokeOpacity=".5" /><path d="M136 184Q98 154 136 96Q128 62 148 64Q168 65 168 103Q221 160 190 188Z" fill="#cc976e66" stroke="#e4b090" /><path d="M206 183Q174 143 214 90Q209 62 228 70Q244 73 234 105Q267 154 245 186Z" fill="#a993c944" stroke="#cbb1ec" />{[110, 130, 150].map(y => <path key={y} d={`M137 ${y}l20 6m59 -8 17 7`} stroke="#e8cdaa" />)}<circle cx="151" cy="70" r="8" fill="#101521" stroke="#d0a27f" /><circle cx="225" cy="75" r="7" fill="#101521" stroke="#b1a0db" /><text x="180" y="219" textAnchor="middle" fill="#b8c5d5" fontSize="11">일부 멍게류의 바나듐 농축</text></g>}
    {kind === "silver" && <g stroke="#b9c5d6" fill="none"><path d="M87 190 115 76h76l28 114ZM109 154h88M116 130h74" /><path d="M143 145q-20-35 6-47q-5 25 12 30q23-25 16-50q42 59-6 76" fill="#edb17a88" stroke="#e4b481" /><path d="m217 171 40-19 30 16-41 20Z" fill="#b9c5d699" /><path d="m235 203 32-17 27 16-31 14Z" fill="#c8d8f255" /><text x="180" y="37" textAnchor="middle" fill="#b8c5d5" stroke="none" fontSize="14">argentum · Ag · Argentina</text></g>}
    {kind === "grain" && <g stroke="#bed5a1" fill="none" strokeWidth="2"><path d="M180 200V67m0 115-36-31m36 9 37-29m-37 11-30-28m30 8 32-25m-32 10-24-24" />{[87, 111, 139, 167].map((y, i) => <g key={y}><ellipse cx="162" cy={y} rx="15" ry="7" transform={`rotate(38 162 ${y})`} fill="#baca8544" /><ellipse cx="198" cy={y - 9} rx="15" ry="7" transform={`rotate(-38 198 ${y - 9})`} fill="#baca8544" /><circle cx={74 + i * 68} cy="46" r="3" fill="#c3bfd9" stroke="none" /></g>)}<text x="180" y="224" textAnchor="middle" fill="#b8c5d5" stroke="none" fontSize="11">공기와 땅에서 식물의 재료로</text></g>}
    {kind === "battery" && <g stroke="#a7d3c4" fill="none"><rect x="104" y="69" width="151" height="106" rx="14" /><path d="M255 105h13v34h-13M129 93h39v58h-39m60-37h42m-21-21v42" /><path d="m180 185-12 24h18l-8 20 30-32h-19l8-12" fill="#e8c58a" stroke="none" /><text x="180" y="45" textAnchor="middle" fill="#b8c5d5" fontSize="12">저장된 에너지, 움직이는 전자</text></g>}
    {kind === "chip" && <g fill="none" stroke="#b0a0df"><rect x="131" y="72" width="99" height="99" rx="8" /><rect x="153" y="94" width="55" height="55" />{[89, 112, 136, 159].map(v => <path key={v} d={`M${v + 60} 72V46m0 125v27M131 ${v}H101m129 0h31`} />)}<text x="180" y="220" textAnchor="middle" fill="#b8c5d5" fontSize="12">거대한 계산이 작은 재료에서</text></g>}
    {kind === "star" && <g><circle cx="180" cy="122" r="53" fill="#e8c88b" opacity=".8" /><circle cx="180" cy="122" r="72" fill="none" stroke="#e8c88b55" />{Array.from({ length: 12 }, (_, i) => <path key={i} d="M180 32V18" transform={`rotate(${i * 30} 180 122)`} stroke="#e8c88b" />)}<text x="180" y="226" textAnchor="middle" fill="#b8c5d5" fontSize="12">가벼운 원소가 별의 빛으로</text></g>}
    {kind === "magnet" && <g><path d="M112 74v67a68 68 0 0 0 136 0V74h-38v67a30 30 0 0 1-60 0V74Z" fill="#959dc144" stroke="#c0bddc" /><path d="M112 107h38m60 0h38" stroke="#d9b494" /><text x="131" y="94" fill="#e1b3b4" textAnchor="middle">N</text><text x="229" y="94" fill="#aab9e9" textAnchor="middle">S</text><path d="M99 83Q63 23 179 22T262 82" fill="none" stroke="#8ecdc766" /></g>}
    {kind === "nucleus" && <g><ellipse cx="180" cy="120" rx="100" ry="39" fill="none" stroke="#afa7d577" transform="rotate(35 180 120)" /><ellipse cx="180" cy="120" rx="100" ry="39" fill="none" stroke="#afa7d577" transform="rotate(-35 180 120)" />{Array.from({ length: 13 }, (_, i) => <circle key={i} cx={180 + Math.cos(i * 2.4) * Math.sqrt(i) * 8} cy={120 + Math.sin(i * 2.4) * Math.sqrt(i) * 8} r="9" fill={i % 2 ? "#d4a1aa" : "#9caed7"} />)}<text x="180" y="222" textAnchor="middle" fill="#b8c5d5" fontSize="11">원자핵의 개념 표현 · 비율은 실제와 다름</text></g>}
    {kind === "crystal" && <g stroke="#bfb7de" fill="#afa2d21c"><path d="m180 43-72 75 28 68h88l28-68Z" /><path d="m180 43-28 75 28 68 28-68Zm-72 75h144m-116 68 16-68m72 68-16-68" /><text x="180" y="222" textAnchor="middle" fill="#b8c5d5" stroke="none" fontSize="11">구조를 떠올리는 상징 · 실제 결정 사진은 아님</text></g>}
  </svg><figcaption>{caption}</figcaption></figure>;
}

export default function PeriodicRoom({ navigate }: { navigate: Navigate }) {
  const [selected, setSelected] = useState(ELEMENTS[0]), [query, setQuery] = useState(""), [chapter, setChapter] = useState(0);
  const storyRef = useRef<HTMLElement>(null);
  const [seen, setSeen] = useState<string[]>(savedDiscoveries);
  const [detective, setDetective] = useState(false), [caseIndex, setCaseIndex] = useState(0), [caseSolved, setCaseSolved] = useState(false), [caseFeedback, setCaseFeedback] = useState("");
  const needle = query.trim().toLowerCase();
  const exactMatches = ELEMENTS.filter(e => [String(e.number), e.symbol.toLowerCase(), e.name, ...(everydayElement(e.number)?.aliases || [])].includes(needle));
  const matches = needle && exactMatches.length ? exactMatches : ELEMENTS.filter(e => { const life = everydayElement(e.number); return `${e.number} ${e.symbol} ${e.name} ${e.title} ${e.uses} ${life ? `${life.title} ${life.caption} ${life.story} ${life.material} ${life.aliases.join(" ")}` : ""}`.toLowerCase().includes(needle); });
  const life = everydayElement(selected.number);
  const extras = EXTRA_STORIES[selected.symbol] || [];
  const chapters = [...(life ? [{ title: life.title, text: life.story }, { title: "왜 이 원소일까요?", text: life.mechanism }] : []), { title: selected.title, text: selected.story }, { title: "일상과 실험실에서", text: selected.uses }, ...extras, { title: "원소의 한마디 · 창작 농담", text: selected.joke }];
  const select = (element: ElementStory) => { setSelected(element); setChapter(0); setSeen(previous => { const next = previous.includes(element.symbol) ? previous : [...previous, element.symbol]; try { localStorage.setItem(STORAGE, JSON.stringify(next)); } catch { /* Storage may be unavailable; exploration still works. */ } return next; }); if (!detective) storyRef.current?.scrollIntoView?.({ behavior: window.matchMedia?.("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth", block: "start" }); };
  const inSequence = (number: number) => { setQuery(""); select(ELEMENTS[number - 1]); };
  return <div className="cosmos-room"><div className="cosmos-intro"><span className="cosmos-kicker">02 / 54 EVERYDAY CONNECTIONS · 118 ELEMENTS</span><h3>이름 하나에,<br /><em>세계가 따라옵니다.</em></h3><p>수소부터 제논까지, 54개 원소를 생활 속 장면과 전용 그림으로 만납니다. 물건에서 시작해 원리, 이름의 역사, 농담으로 이야기를 넘겨 보세요. 55번 이후의 원소 이야기도 표에서 읽을 수 있습니다.</p></div>
    <div className="periodic-toolbar"><label>원소 찾기 <input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Ag, 은, 나트륨, 터치 화면…" /></label><span aria-live="polite">발견한 원소 {seen.length} / 118</span><button onClick={() => inSequence(1)}>1번부터 차례로 읽기 →</button><button onClick={() => select(ELEMENTS[(selected.number * 37 + seen.length) % ELEMENTS.length])}>뜻밖의 원소 만나기 ↗</button><button onClick={() => { setDetective(v => !v); setCaseIndex(0); setCaseSolved(false); setCaseFeedback(""); }}>{detective ? "탐정 노트 접기" : "원소 탐정 게임 ↗"}</button></div>
    {detective && <section className="cosmos-card detective-game"><span className="cosmos-kicker">ELEMENT DETECTIVE / 단서 {caseIndex + 1} OF {CASES.length}</span><h4>이 이야기의 원소는 누구일까요?</h4><p>{CASES[caseIndex].clue}</p><p className="cosmos-note">표에서 원소를 고른 뒤 확인하세요. 현재 선택: {selected.symbol} · {selected.name}</p><p role="status">{caseFeedback}</p>{!caseSolved ? <button onClick={() => { const correct = selected.symbol === CASES[caseIndex].symbol; setCaseSolved(correct); setCaseFeedback(correct ? `${selected.name}, 맞았습니다. 아래 이야기에서 연결을 더 읽어 보세요.` : "아직 그 원소는 아니에요. 기호를 찾거나 다른 칸의 이야기를 읽어 보세요."); }}>선택한 원소로 확인</button> : caseIndex < CASES.length - 1 ? <button onClick={() => { setCaseIndex(i => i + 1); setCaseSolved(false); setCaseFeedback(""); }}>다음 단서 →</button> : <p className="cosmos-success">다섯 개의 연결을 찾았습니다. 오늘의 칭호: 주기율표의 이야기 탐정.</p>}</section>}
    {needle && <div className="cosmos-chips search-matches" role="region" aria-label="원소 검색 결과" aria-live="polite">{matches.length ? matches.map(e => <button key={e.symbol} onClick={() => select(e)}>{e.symbol} · {e.name}</button>) : <p>찾는 원소가 없습니다. 기호나 이름을 바꿔 보세요.</p>}</div>}
    <p className="cosmos-note mobile-table-hint">작은 화면에서는 표를 좌우로 밀어 보세요. 원소 찾기를 쓰면 바로 선택할 수 있습니다.</p>
    <div className="periodic-scroll" role="region" aria-label="118개 원소 주기율표" tabIndex={0}><div className="periodic-grid">
      {Array.from({ length: 18 }, (_, i) => <span className="periodic-group" style={{ gridRow: 1, gridColumn: i + 1 }} key={`group-${i}`}>{i + 1}</span>)}
      {ELEMENTS.map(e => <button key={e.symbol} className={`element-tile ${selected.symbol === e.symbol ? "selected" : ""} ${query && !matches.includes(e) ? "dimmed" : ""}`} style={{ gridRow: e.row + 1, gridColumn: e.column }} onClick={() => select(e)} aria-pressed={selected.symbol === e.symbol} aria-label={`${e.number} ${e.symbol} ${e.name}`} data-family={e.family}><small>{e.number}{seen.includes(e.symbol) && <i aria-label="발견함">·</i>}</small><strong>{e.symbol}</strong><span>{e.name}</span></button>)}
      <span className="periodic-bridge" style={{ gridRow: 7, gridColumn: 3 }}>57–71<br />↓</span><span className="periodic-bridge" style={{ gridRow: 8, gridColumn: 3 }}>89–103<br />↓</span>
    </div></div>
    <article ref={storyRef} className="cosmos-card element-story"><div className="element-heading"><div><span className="cosmos-kicker">ATOMIC NUMBER {selected.number} / {selected.family}</span><h4><b>{selected.symbol}</b> {selected.name}</h4></div><span className="cosmos-badge">{chapter + 1} / {chapters.length} 장</span></div>
      {life && <nav className="life-sequence" aria-label="생활 원소 순서"><button disabled={selected.number === 1} onClick={() => inSequence(selected.number - 1)}>← 이전 원소</button><span>{String(selected.number).padStart(2, "0")} <i>/ 54 · 생활 속 원소</i></span><button onClick={() => inSequence(selected.number === 54 ? 1 : selected.number + 1)}>{selected.number === 54 ? "수소부터 다시 ↻" : "다음 원소 →"}</button></nav>}
      <div className="element-story-body">{life && !(extras.length && chapter >= 4 && chapter < 4 + extras.length) ? <EverydayIllustration element={selected} life={life} /> : <ElementIllustration element={selected} />}<div className="element-chapter"><div className="chapter-dots">{chapters.map((part, i) => <button key={`${selected.symbol}-${i}`} aria-label={`${i + 1}장 ${part.title}`} aria-pressed={chapter === i} onClick={() => setChapter(i)}>{String(i + 1).padStart(2, "0")}</button>)}</div><h4>{chapters[chapter].title}</h4><p>{chapters[chapter].text}</p>{life && chapter < 2 && <aside className="everyday-prompt"><span>내 주변에서 찾아보기</span><p>{life.lookFor}</p></aside>}<div className="cosmos-controls"><button disabled={chapter === 0} onClick={() => setChapter(i => i - 1)}>← 이전 이야기</button><button onClick={() => setChapter(i => (i + 1) % chapters.length)}>{chapter === chapters.length - 1 ? "처음 이야기로 ↻" : "다음 이야기 →"}</button></div></div></div>
      <div className="cosmos-chips"><button onClick={() => select(ELEMENTS[22])}>V · 멍게에서 여신까지</button><button onClick={() => select(ELEMENTS[46])}>Ag · 은과 두 기술자</button><button onClick={() => select(ELEMENTS[6])}>N · 공기의 조용한 다수</button>{selected.symbol === "Cs" && <button onClick={() => navigate("clock")}>이 원소로 1초를 세기 →</button>}{["H", "He", "Au", "Fe", "C"].includes(selected.symbol) && <button onClick={() => navigate("stars")}>원소의 무대, 별로 이동 →</button>}</div><Sources links={selected.sources} />
    </article><p className="cosmos-note">1–54번 그림은 생활 속 쓰임을 설명하기 위해 직접 그린 삽화입니다. 물건과 미시 구조를 함께 보여 주며 실제 크기·비율과는 다릅니다. 순수 원소, 합금, 화합물, 동위원소를 구분해 설명합니다. ‘원소의 한마디’는 직접 쓴 농담입니다.</p>
  </div>;
}
